"""Generate docs/URS.md from the laboratory's workflow description.

Every numbered step becomes a requirement ID `WF-<section>.<step>` (e.g. WF-07.07).
Tests reference these IDs with `@pytest.mark.urs(...)`, which lets
tools/traceability.py produce the requirement-to-test matrix used in validation.

    python tools/gen_urs.py            # rewrite docs/URS.md
    python tools/gen_urs.py --check    # fail if docs/URS.md is out of date
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "workflow" / "LIMS_WORKFLOW_STEPS.md"
TARGET = ROOT / "docs" / "URS.md"

SECTION = re.compile(r"^##\s+(\d+)\.\s+(.+?)\s*$")
STEP = re.compile(r"^(\d+)\.\s+(.+?)\s*$")


def parse(text: str) -> list[tuple[int, str, list[tuple[str, str]]]]:
    sections: list[tuple[int, str, list[tuple[str, str]]]] = []
    for line in text.splitlines():
        if m := SECTION.match(line):
            sections.append((int(m[1]), m[2], []))
        elif (m := STEP.match(line)) and sections:
            number, _, steps = sections[-1]
            steps.append((f"WF-{number:02d}.{int(m[1]):02d}", m[2]))
    return sections


def render(sections: list[tuple[int, str, list[tuple[str, str]]]]) -> str:
    out = [
        "# User Requirements Specification",
        "",
        "Generated by `tools/gen_urs.py` from `docs/workflow/LIMS_WORKFLOW_STEPS.md`. "
        "Do not edit by hand: change the workflow document and regenerate.",
        "",
        "Each step is a requirement. Tests cite IDs with `@pytest.mark.urs(\"WF-07.07\")`; "
        "`tools/traceability.py` builds the requirement-to-test matrix.",
        "",
    ]
    for number, title, steps in sections:
        out += [f"## {number}. {title}", "", "| ID | Requirement |", "|---|---|"]
        out += [f"| {rid} | {text.replace('|', '\\|')} |" for rid, text in steps]
        out.append("")
    return "\n".join(out)


def requirement_ids() -> list[str]:
    return [rid for _, _, steps in parse(SOURCE.read_text()) for rid, _ in steps]


def main() -> int:
    content = render(parse(SOURCE.read_text()))
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != content:
            print("docs/URS.md is out of date; run python tools/gen_urs.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(content)
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(requirement_ids())} requirements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
