#!/usr/bin/env python3
"""Pipeline self-test: fabricates a tiny synthetic donor .msapp (from the
documented Studio label/screen structure), harvests it, compiles a 2-screen
spec, verifies, packs, and builds the .txt bundle.

This validates that the CODE runs end-to-end. It does NOT prove Power Apps
will import the output — only the probe ladder against a real tenant does.

Usage: python selftest.py [workdir]
"""
import json
import os
import shutil
import sys
import tempfile
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from harvest_donor import harvest            # noqa: E402
from msapp_compiler import Compiler, pack_msapp, make_txt_bundle  # noqa: E402
from verify_msapp import verify              # noqa: E402

LABEL = {
    "Type": "ControlInfo", "Name": "lblTemp1", "HasDynamicProperties": False,
    "Template": {
        "Id": "http://microsoft.com/appmagic/label", "Version": "2.5.1",
        "LastModifiedTimestamp": "0", "Name": "label", "FirstParty": True,
        "IsPremiumPcfControl": False, "IsCustomGroupControlTemplateName": False,
        "CustomGroupControlTemplateName": "", "IsComponentDefinition": False,
        "OverridableProperties": {},
    },
    "Index": 0, "PublishOrderIndex": 2, "VariantName": "", "LayoutName": "",
    "MetaDataIDKey": "", "PersistMetaDataIDKey": False,
    "IsFromScreenLayout": False, "StyleName": "defaultLabelStyle",
    "Parent": "scrDonor", "IsDataControl": False, "AllowAccessToGlobals": True,
    "OptimizeForDevices": "Off", "IsGroupControl": False,
    "IsAutoGenerated": False,
    "Rules": [
        {"Property": "Text", "Category": "Data",
         "InvariantScript": "\"Donor\"", "RuleProviderType": "Unknown"},
        {"Property": "X", "Category": "Design",
         "InvariantScript": "40", "RuleProviderType": "Unknown"},
        {"Property": "Y", "Category": "Design",
         "InvariantScript": "40", "RuleProviderType": "Unknown"},
        {"Property": "Width", "Category": "Design",
         "InvariantScript": "150", "RuleProviderType": "Unknown"},
        {"Property": "Height", "Category": "Design",
         "InvariantScript": "40", "RuleProviderType": "Unknown"},
    ],
    "ControlPropertyState": [
        {"InvariantPropertyName": "Text", "AutoRuleBindingEnabled": False,
         "AutoRuleBindingString": "", "NameMapSourceSchema": "?",
         "IsLockable": False, "AFDDataSourceName": ""},
        "X", "Y", "Width", "Height",
    ],
    "IsLocked": False, "ControlUniqueId": "8", "Children": [],
}

SCREEN = {
    "Type": "ControlInfo", "Name": "scrDonor",
    "Template": {"Id": "http://microsoft.com/appmagic/screen",
                 "Version": "1.0", "Name": "screen", "FirstParty": True,
                 "OverridableProperties": {}},
    "Index": 0, "PublishOrderIndex": 1, "VariantName": "", "LayoutName": "",
    "StyleName": "defaultScreenStyle", "Parent": "",
    "Rules": [{"Property": "Fill", "Category": "Design",
               "InvariantScript": "RGBA(255, 255, 255, 1)",
               "RuleProviderType": "Unknown"}],
    "ControlPropertyState": ["Fill"],
    "ControlUniqueId": "4", "Children": [LABEL],
}

APP = {
    "Type": "ControlInfo", "Name": "App",
    "Template": {"Id": "http://microsoft.com/appmagic/appinfo",
                 "Version": "1.0", "Name": "appinfo", "FirstParty": True,
                 "OverridableProperties": {}},
    "Index": 0, "PublishOrderIndex": 0, "StyleName": "", "Parent": "",
    "Rules": [{"Property": "OnStart", "Category": "Behavior",
               "InvariantScript": "Set(varDonor, true)",
               "RuleProviderType": "Unknown"}],
    "ControlPropertyState": ["OnStart"],
    "ControlUniqueId": "1", "Children": [],
}

DONOR_FILES = {
    "Header.json": json.dumps({"DocVersion": "1.337", "MinVersionToLoad": "1.337"}),
    "Properties.json": json.dumps(
        {"Name": "Donor", "ControlCount": {"screen": 1, "label": 1}}),
    "AppCheckerResult.sarif": "{}",
    "Controls/1.json": json.dumps({"TopParent": APP}),
    "Controls/4.json": json.dumps({"TopParent": SCREEN}),
    "References/DataSources.json": json.dumps({"DataSources": []}),
    "References/Templates.json": json.dumps({"UsedTemplates": [
        {"Id": "http://microsoft.com/appmagic/label", "Version": "2.5.1"}]}),
    "References/Themes.json": json.dumps({"CurrentTheme": "defaultTheme"}),
    "References/ModernThemes.json": "{}",
    "References/Resources.json": json.dumps({"Resources": []}),
    "Resources/PublishInfo.json": json.dumps({"AppName": "Donor"}),
    "Src/App.pa.yaml": (
        "App:\n  Properties:\n    OnStart: |-\n      =Set(varDonor, true)\n"),
    "Src/_EditorState.pa.yaml": "ScreenOrder:\n  - scrDonor\n",
    "Src/scrDonor.pa.yaml": (
        "Screens:\n  scrDonor:\n    Properties:\n"
        "      Fill: =RGBA(255, 255, 255, 1)\n    Children:\n"
        "      - lblTemp1:\n          Control: Label@2.5.1\n"
        "          Properties:\n            Text: =\"Donor\"\n"
        "            X: =40\n            Y: =40\n"),
}

SPEC = {
    "name": "SelfTest",
    "onstart": "Set(varReady, true);\nClearCollect(colX, [1, 2, 3])",
    "screens": [
        {"name": "scrHome",
         "properties": {"Fill": "RGBA(245, 246, 250, 1)"},
         "controls": [
             {"type": "label", "name": "lblTitle",
              "properties": {"Text": "\"Self Test\"", "X": "40", "Y": "24",
                             "Size": "24"}},
             {"type": "label", "name": "lblGo",
              "properties": {"Text": "\"Go\"",
                             "OnSelect": "Navigate(scrTwo)"}},
         ]},
        {"name": "scrTwo",
         "controls": [
             {"type": "label", "name": "lblBack",
              "properties": {"Text": "\"Back\"",
                             "OnSelect": "Navigate(scrHome)"}},
         ]},
    ],
}


def main():
    work = sys.argv[1] if len(sys.argv) > 1 else tempfile.mkdtemp(prefix="msapp-selftest-")
    os.makedirs(work, exist_ok=True)

    donor_path = os.path.join(work, "donor.msapp")
    with zipfile.ZipFile(donor_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for arc, content in DONOR_FILES.items():
            zf.writestr(arc, content)
    print(f"[1/5] synthetic donor: {donor_path}")

    harvest_dir = os.path.join(work, "harvest")
    harvest(donor_path, harvest_dir)
    print("[2/5] harvest OK")

    out_dir = os.path.join(work, "build")
    comp = Compiler(harvest_dir)
    extracted = comp.compile(SPEC, out_dir)
    for w in comp.warnings:
        print(f"      WARN {w}")
    print("[3/5] compile OK")

    errors, warnings = verify(extracted)
    for w in warnings:
        print(f"      WARN {w}")
    for e in errors:
        print(f"      ERROR {e}")
    if errors:
        sys.exit("[4/5] VERIFY FAILED")
    print("[4/5] verify OK (0 errors)")

    msapp = os.path.join(out_dir, "SelfTest.msapp")
    pack_msapp(extracted, msapp)
    txt_dir, script = make_txt_bundle(extracted, out_dir, "SelfTest")
    assert os.path.getsize(msapp) > 0
    assert os.listdir(txt_dir)
    assert os.path.exists(script)
    print(f"[5/5] packed {msapp} + {len(os.listdir(txt_dir))} txt files + rebuild script")
    print("SELFTEST PASSED")
    shutil.rmtree(work, ignore_errors=True) if len(sys.argv) < 2 else None


if __name__ == "__main__":
    main()
