"""core: identity, audit, files, documents, grants, ids, jobs

Revision ID: 0001
Revises:
Create Date: 2026-10-07 20:10:15.488768

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.core.migration_helpers import (
    create_forbid_mutation_function,
    drop_append_only,
    make_append_only,
)

# Rows in these tables are never updated or deleted (audit trail, original
# files, document versions and signatures). Keep in sync with @append_only.
APPEND_ONLY = ["audit_event", "stored_file", "document", "document_version", "signature"]

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("oidc_subject", sa.String(length=200), nullable=True),
        sa.Column("status", sa.Enum("active", "disabled", name="account_status"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("oidc_subject", name=op.f("uq_app_user_oidc_subject")),
        sa.UniqueConstraint("username", name=op.f("uq_app_user_username")),
    )
    op.create_table(
        "id_sequence",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=False),
        sa.Column("last_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name", "period", name=op.f("pk_id_sequence")),
    )
    op.create_table(
        "laboratory",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_laboratory")),
        sa.UniqueConstraint("code", name=op.f("uq_laboratory_code")),
    )
    op.create_table(
        "access_grant",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.Enum("assignment", "codis_share", name="grant_kind"), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_by", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["app_user.id"], name=op.f("fk_access_grant_granted_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"], ["app_user.id"], name=op.f("fk_access_grant_revoked_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_access_grant_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_grant")),
    )
    op.create_index(
        "ix_access_grant_lookup",
        "access_grant",
        ["user_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "uq_access_grant_active",
        "access_grant",
        ["user_id", "entity_type", "entity_id", "kind"],
        unique=True,
        postgresql_where="revoked_at IS NULL",
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["app_user.id"], name=op.f("fk_audit_event_actor_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
        sa.UniqueConstraint("hash", name=op.f("uq_audit_event_hash")),
    )
    op.create_index(op.f("ix_audit_event_action"), "audit_event", ["action"], unique=False)
    op.create_table(
        "document",
        sa.Column("doc_type", sa.String(length=100), nullable=False),
        sa.Column("subject_type", sa.String(length=100), nullable=False),
        sa.Column("subject_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name=op.f("fk_document_created_by_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
    )
    op.create_index(op.f("ix_document_subject_id"), "document", ["subject_id"], unique=False)
    op.create_table(
        "job",
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "resolved", name="job_status"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["app_user.id"], name=op.f("fk_job_requested_by_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index(op.f("ix_job_kind"), "job", ["kind"], unique=False)
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)
    op.create_table(
        "stored_file",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=200), nullable=False),
        sa.Column("original_name", sa.String(length=500), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["app_user.id"], name=op.f("fk_stored_file_uploaded_by_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_file")),
    )
    op.create_index(op.f("ix_stored_file_sha256"), "stored_file", ["sha256"], unique=False)
    op.create_table(
        "user_laboratory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["laboratory_id"],
            ["laboratory.id"],
            name=op.f("fk_user_laboratory_laboratory_id_laboratory"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_laboratory_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_laboratory")),
        sa.UniqueConstraint("user_id", "laboratory_id", name=op.f("uq_user_laboratory_user_id")),
    )
    op.create_table(
        "user_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "case_scientist",
                "screening_lab_officer",
                "dna_lab_officer",
                "reviewer",
                "codis_scientist",
                "lims_admin",
                name="role",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_user_role_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role")),
        sa.UniqueConstraint("user_id", "role", name=op.f("uq_user_role_user_id")),
    )
    op.create_table(
        "document_version",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name=op.f("fk_document_version_created_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.id"], name=op.f("fk_document_version_document_id_document")
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["stored_file.id"], name=op.f("fk_document_version_file_id_stored_file")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_version")),
        sa.UniqueConstraint(
            "document_id", "version_no", name=op.f("uq_document_version_document_id")
        ),
    )
    op.create_index(
        op.f("ix_document_version_document_id"), "document_version", ["document_id"], unique=False
    )
    op.create_table(
        "signature",
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("signer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "meaning",
            sa.Enum(
                "completed",
                "reviewed",
                "approved",
                "authorized",
                "independent_check",
                "administrative_review",
                "technical_review",
                "final_signoff",
                name="signature_meaning",
            ),
            nullable=False,
        ),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("reauthenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "signed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_version.id"],
            name=op.f("fk_signature_document_version_id_document_version"),
        ),
        sa.ForeignKeyConstraint(
            ["signer_id"], ["app_user.id"], name=op.f("fk_signature_signer_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signature")),
        sa.UniqueConstraint(
            "document_version_id",
            "signer_id",
            "meaning",
            name=op.f("uq_signature_document_version_id"),
        ),
    )
    op.create_index(
        op.f("ix_signature_document_version_id"), "signature", ["document_version_id"], unique=False
    )
    # ### end Alembic commands ###
    create_forbid_mutation_function()
    for table in APPEND_ONLY:
        make_append_only(table)


def downgrade() -> None:
    """Downgrade schema."""
    for table in APPEND_ONLY:
        drop_append_only(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signature_document_version_id"), table_name="signature")
    op.drop_table("signature")
    op.drop_index(op.f("ix_document_version_document_id"), table_name="document_version")
    op.drop_table("document_version")
    op.drop_table("user_role")
    op.drop_table("user_laboratory")
    op.drop_index(op.f("ix_stored_file_sha256"), table_name="stored_file")
    op.drop_table("stored_file")
    op.drop_index(op.f("ix_job_status"), table_name="job")
    op.drop_index(op.f("ix_job_kind"), table_name="job")
    op.drop_table("job")
    op.drop_index(op.f("ix_document_subject_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_audit_event_action"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index(
        "uq_access_grant_active", table_name="access_grant", postgresql_where="revoked_at IS NULL"
    )
    op.drop_index("ix_access_grant_lookup", table_name="access_grant")
    op.drop_table("access_grant")
    op.drop_table("laboratory")
    op.drop_table("id_sequence")
    op.drop_table("app_user")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS lims_forbid_mutation()")
    for enum in ["role", "account_status", "signature_meaning", "grant_kind", "job_status"]:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
