"""casework: reference data, items, cases, receipts, custody

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 20:31:53.474100

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.migration_helpers import drop_append_only, make_append_only

APPEND_ONLY = ["custody_movement"]


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
        sa.UniqueConstraint("code", name=op.f("uq_client_code")),
    )
    op.create_table(
        "case",
        sa.Column("case_number", sa.String(length=30), nullable=False),
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("client_reference", sa.String(length=100), nullable=False),
        sa.Column(
            "source", sa.Enum("paper", "electronic", name="submission_source"), nullable=False
        ),
        sa.Column("submission_reference", sa.String(length=100), nullable=True),
        sa.Column("submitter_name", sa.String(length=200), nullable=False),
        sa.Column("submitter_contact", sa.String(length=300), nullable=True),
        sa.Column("investigating_officer_name", sa.String(length=200), nullable=False),
        sa.Column("investigating_officer_contact", sa.String(length=300), nullable=True),
        sa.Column("case_information", sa.Text(), nullable=True),
        sa.Column("state", sa.Enum("open", "closed", name="case_state"), nullable=False),
        sa.Column("registered_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], name=op.f("fk_case_client_id_client")
        ),
        sa.ForeignKeyConstraint(
            ["laboratory_id"], ["laboratory.id"], name=op.f("fk_case_laboratory_id_laboratory")
        ),
        sa.ForeignKeyConstraint(
            ["registered_by"], ["app_user.id"], name=op.f("fk_case_registered_by_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case")),
        sa.UniqueConstraint("case_number", name=op.f("uq_case_case_number")),
    )
    op.create_index(op.f("ix_case_laboratory_id"), "case", ["laboratory_id"], unique=False)
    op.create_table(
        "handover",
        sa.Column("from_person_id", sa.Uuid(), nullable=False),
        sa.Column("to_person_id", sa.Uuid(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_person_id"], ["app_user.id"], name=op.f("fk_handover_from_person_id_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["to_person_id"], ["app_user.id"], name=op.f("fk_handover_to_person_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handover")),
    )
    op.create_index(op.f("ix_handover_to_person_id"), "handover", ["to_person_id"], unique=False)
    op.create_table(
        "location",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("storage", "bench", "instrument", "transit", "disposal", name="location_kind"),
            nullable=False,
        ),
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["laboratory_id"], ["laboratory.id"], name=op.f("fk_location_laboratory_id_laboratory")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location")),
        sa.UniqueConstraint("code", name=op.f("uq_location_code")),
    )
    op.create_table(
        "subcase",
        sa.Column("subcase_number", sa.String(length=30), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("laboratory_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.Enum("open", "closed", name="subcase_state"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["case.id"], name=op.f("fk_subcase_case_id_case")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["app_user.id"], name=op.f("fk_subcase_created_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["laboratory_id"], ["laboratory.id"], name=op.f("fk_subcase_laboratory_id_laboratory")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subcase")),
        sa.UniqueConstraint("subcase_number", name=op.f("uq_subcase_subcase_number")),
    )
    op.create_index(op.f("ix_subcase_case_id"), "subcase", ["case_id"], unique=False)
    op.create_table(
        "item",
        sa.Column("barcode", sa.String(length=50), nullable=False),
        sa.Column(
            "kind", sa.Enum("exhibit", "sample", "material", name="item_kind"), nullable=False
        ),
        sa.Column("subcase_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["item.id"], name=op.f("fk_item_parent_id_item")),
        sa.ForeignKeyConstraint(
            ["subcase_id"], ["subcase.id"], name=op.f("fk_item_subcase_id_subcase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item")),
        sa.UniqueConstraint("barcode", name=op.f("uq_item_barcode")),
    )
    op.create_index(op.f("ix_item_subcase_id"), "item", ["subcase_id"], unique=False)
    op.create_table(
        "receipt",
        sa.Column("receipt_number", sa.String(length=30), nullable=False),
        sa.Column("subcase_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("draft", "completed", "exception", "cancelled", name="receipt_state"),
            nullable=False,
        ),
        sa.Column("prepared_by", sa.Uuid(), nullable=False),
        sa.Column("actual_submitter_name", sa.String(length=200), nullable=True),
        sa.Column("receiving_staff_id", sa.Uuid(), nullable=True),
        sa.Column("signature_file_id", sa.Uuid(), nullable=True),
        sa.Column("record_document_id", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "exception_kind",
            sa.Enum(
                "submitter_refused", "signature_failed", "handover_other", name="receipt_exception"
            ),
            nullable=True,
        ),
        sa.Column("exception_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prepared_by"], ["app_user.id"], name=op.f("fk_receipt_prepared_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["receiving_staff_id"],
            ["app_user.id"],
            name=op.f("fk_receipt_receiving_staff_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["record_document_id"],
            ["document.id"],
            name=op.f("fk_receipt_record_document_id_document"),
        ),
        sa.ForeignKeyConstraint(
            ["signature_file_id"],
            ["stored_file.id"],
            name=op.f("fk_receipt_signature_file_id_stored_file"),
        ),
        sa.ForeignKeyConstraint(
            ["subcase_id"], ["subcase.id"], name=op.f("fk_receipt_subcase_id_subcase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt")),
        sa.UniqueConstraint("receipt_number", name=op.f("uq_receipt_receipt_number")),
    )
    op.create_index(op.f("ix_receipt_subcase_id"), "receipt", ["subcase_id"], unique=False)
    op.create_table(
        "custody_movement",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("receipt", "move", "handover", "correction", name="movement_kind"),
            nullable=False,
        ),
        sa.Column("from_person_id", sa.Uuid(), nullable=True),
        sa.Column("from_location_id", sa.Uuid(), nullable=True),
        sa.Column("to_person_id", sa.Uuid(), nullable=True),
        sa.Column("to_location_id", sa.Uuid(), nullable=True),
        sa.Column("moved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("corrects_movement_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "to_person_id IS NOT NULL OR to_location_id IS NOT NULL",
            name=op.f("ck_custody_movement_has_destination"),
        ),
        sa.ForeignKeyConstraint(
            ["corrects_movement_id"],
            ["custody_movement.id"],
            name=op.f("fk_custody_movement_corrects_movement_id_custody_movement"),
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["location.id"],
            name=op.f("fk_custody_movement_from_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["from_person_id"],
            ["app_user.id"],
            name=op.f("fk_custody_movement_from_person_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_custody_movement_item_id_item")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["app_user.id"], name=op.f("fk_custody_movement_recorded_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["location.id"],
            name=op.f("fk_custody_movement_to_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["to_person_id"],
            ["app_user.id"],
            name=op.f("fk_custody_movement_to_person_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custody_movement")),
    )
    op.create_index(
        op.f("ix_custody_movement_group_id"), "custody_movement", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_custody_movement_item_id"), "custody_movement", ["item_id"], unique=False
    )
    op.create_table(
        "exhibit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subcase_id", sa.Uuid(), nullable=False),
        sa.Column("submitter_item_ref", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("marking", sa.String(length=300), nullable=True),
        sa.Column("seal", sa.String(length=300), nullable=True),
        sa.Column(
            "state",
            sa.Enum("submitted", "accepted", "rejected", "received", name="exhibit_state"),
            nullable=False,
        ),
        sa.Column("description_matches", sa.Boolean(), nullable=True),
        sa.Column("marking_matches", sa.Boolean(), nullable=True),
        sa.Column("seal_intact", sa.Boolean(), nullable=True),
        sa.Column("check_notes", sa.Text(), nullable=True),
        sa.Column("checked_by", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("receipt_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["checked_by"], ["app_user.id"], name=op.f("fk_exhibit_checked_by_app_user")
        ),
        sa.ForeignKeyConstraint(["id"], ["item.id"], name=op.f("fk_exhibit_id_item")),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipt.id"], name=op.f("fk_exhibit_receipt_id_receipt")
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["app_user.id"], name=op.f("fk_exhibit_recorded_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["subcase_id"], ["subcase.id"], name=op.f("fk_exhibit_subcase_id_subcase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exhibit")),
    )
    op.create_index(op.f("ix_exhibit_subcase_id"), "exhibit", ["subcase_id"], unique=False)
    op.create_table(
        "custody_correction",
        sa.Column("movement_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("requested", "authorized", "declined", name="correction_state"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("to_person_id", sa.Uuid(), nullable=True),
        sa.Column("to_location_id", sa.Uuid(), nullable=True),
        sa.Column("moved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("correction_movement_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["correction_movement_id"],
            ["custody_movement.id"],
            name=op.f("fk_custody_correction_correction_movement_id_custody_movement"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["app_user.id"], name=op.f("fk_custody_correction_decided_by_app_user")
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["custody_movement.id"],
            name=op.f("fk_custody_correction_movement_id_custody_movement"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["app_user.id"],
            name=op.f("fk_custody_correction_requested_by_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["location.id"],
            name=op.f("fk_custody_correction_to_location_id_location"),
        ),
        sa.ForeignKeyConstraint(
            ["to_person_id"],
            ["app_user.id"],
            name=op.f("fk_custody_correction_to_person_id_app_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custody_correction")),
    )
    op.create_index(
        op.f("ix_custody_correction_movement_id"),
        "custody_correction",
        ["movement_id"],
        unique=False,
    )
    op.create_table(
        "handover_item",
        sa.Column("handover_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("pending", "accepted", "withdrawn", name="handover_item_state"),
            nullable=False,
        ),
        sa.Column("movement_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["handover_id"], ["handover.id"], name=op.f("fk_handover_item_handover_id_handover")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_handover_item_item_id_item")
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["custody_movement.id"],
            name=op.f("fk_handover_item_movement_id_custody_movement"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handover_item")),
    )
    op.create_index(
        op.f("ix_handover_item_handover_id"), "handover_item", ["handover_id"], unique=False
    )
    op.create_index(op.f("ix_handover_item_item_id"), "handover_item", ["item_id"], unique=False)
    op.create_table(
        "receipt_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("exhibit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exhibit_id"], ["exhibit.id"], name=op.f("fk_receipt_item_exhibit_id_exhibit")
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["receipt.id"], name=op.f("fk_receipt_item_receipt_id_receipt")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_item")),
        sa.UniqueConstraint("receipt_id", "exhibit_id", name=op.f("uq_receipt_item_receipt_id")),
    )
    op.create_index(
        op.f("ix_receipt_item_exhibit_id"), "receipt_item", ["exhibit_id"], unique=False
    )
    op.create_index(
        op.f("ix_receipt_item_receipt_id"), "receipt_item", ["receipt_id"], unique=False
    )
    # ### end Alembic commands ###
    for table in APPEND_ONLY:
        make_append_only(table)


def downgrade() -> None:
    """Downgrade schema."""
    for table in APPEND_ONLY:
        drop_append_only(table)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_item_receipt_id"), table_name="receipt_item")
    op.drop_index(op.f("ix_receipt_item_exhibit_id"), table_name="receipt_item")
    op.drop_table("receipt_item")
    op.drop_index(op.f("ix_handover_item_item_id"), table_name="handover_item")
    op.drop_index(op.f("ix_handover_item_handover_id"), table_name="handover_item")
    op.drop_table("handover_item")
    op.drop_index(op.f("ix_custody_correction_movement_id"), table_name="custody_correction")
    op.drop_table("custody_correction")
    op.drop_index(op.f("ix_exhibit_subcase_id"), table_name="exhibit")
    op.drop_table("exhibit")
    op.drop_index(op.f("ix_custody_movement_item_id"), table_name="custody_movement")
    op.drop_index(op.f("ix_custody_movement_group_id"), table_name="custody_movement")
    op.drop_table("custody_movement")
    op.drop_index(op.f("ix_receipt_subcase_id"), table_name="receipt")
    op.drop_table("receipt")
    op.drop_index(op.f("ix_item_subcase_id"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_subcase_case_id"), table_name="subcase")
    op.drop_table("subcase")
    op.drop_table("location")
    op.drop_index(op.f("ix_handover_to_person_id"), table_name="handover")
    op.drop_table("handover")
    op.drop_index(op.f("ix_case_laboratory_id"), table_name="case")
    op.drop_table("case")
    op.drop_table("client")
    # ### end Alembic commands ###
    for enum in [
        "case_state",
        "correction_state",
        "exhibit_state",
        "handover_item_state",
        "item_kind",
        "location_kind",
        "movement_kind",
        "receipt_exception",
        "receipt_state",
        "subcase_state",
        "submission_source",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
